const express = require ('express')
const adminRouter = express()
const adminController = require('../Controller/admin.controller')
const { products } = require('../Controller/products')
adminRouter.post('/signup', adminController.signup)
adminRouter.post('/staffSignup', adminController.staffSignup)
adminRouter.post('/signin', adminController.signin)
adminRouter.get('/home', adminController.authorizeUser)
adminRouter.get('/customers', adminController.customer)
adminRouter.post('/products', adminController.products)
adminRouter.post('/deleteStaff', adminController.deleteStaff)
adminRouter.post('/deleteProduct', adminController.deleteProduct)
adminRouter.post('/editProduct', adminController.editProduct)
adminRouter.post('/save', adminController.saveProfile)
adminRouter.post('/uploadProfilePhoto', adminController.profilePhoto)
adminRouter.post('/deleteAccount', adminController.deleteAccount)
adminRouter.post('/staffSignin', adminController.staffSignin)
adminRouter.get('/', adminController.adminProfile)
adminRouter.post('/forgotPsw', adminController.forgotPsw)
adminRouter.get('/resetPsw', adminController.resetPsw)
adminRouter.get('/forgotPryKey', adminController.forgotPryKey)
module.exports = adminRouter